version: '3.8'

services:
  pgvector:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: logistics_vector_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgvector-data:
